export const EXPENSE_COLOR_LIST: number[] = [
  0x4b6f3f, 0x638750, 0x7ea568, 0x94b982, 0xabd39c, 0xc6e5b9, 0xdff3d7,
  0xf2fdee,
];

export const INCOME_COLOR_LIST: number[] = [
  0xb3511e, 0xd77525, 0xf2992c, 0xfbb935, 0xffce52, 0xffe38e, 0xfff1ca,
  0xfffbef,
];

// argb
export const EXPENSE_BAR_INIT_COLOR: number = 0x8094b982;

// argb
export const INCOME_BAR_INIT_COLOR: number = 0x80f2992c;

// rgb
export const EXPENSE_BAR_HIGHLIGHT_COLOR: number = 0x94b982;

// rgb
export const INCOME_BAR_HIGHLIGHT_COLOR: number = 0xf2992c;
